-- Add hen_batch_sales table and trigger support for partial batch sales

CREATE OR REPLACE FUNCTION public.update_batch_count_on_sale() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    remaining_count integer;
BEGIN
    IF NEW.count <= 0 THEN
        RAISE EXCEPTION 'Sale count must be greater than 0';
    END IF;

    SELECT current_count - NEW.count
    INTO remaining_count
    FROM hen_batches
    WHERE id = NEW.batch_id
    FOR UPDATE;

    IF remaining_count IS NULL THEN
        RAISE EXCEPTION 'Hen batch % not found', NEW.batch_id;
    END IF;

    IF remaining_count < 0 THEN
        RAISE EXCEPTION 'Cannot sell % hens from batch %, only % hens available',
            NEW.count, NEW.batch_id, remaining_count + NEW.count;
    END IF;

    UPDATE hen_batches
    SET current_count = remaining_count,
        updated_at = CURRENT_TIMESTAMP
    WHERE id = NEW.batch_id;

    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.hen_batch_sales (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id integer NOT NULL,
    sale_date date NOT NULL,
    count integer NOT NULL CHECK (count > 0),
    price_per_hen numeric(12,2) NOT NULL CHECK (price_per_hen >= 0),
    total_amount numeric(12,2) NOT NULL CHECK (total_amount >= 0),
    notes text,
    recorded_by_user_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_hen_batch_sales_batch_id
    ON public.hen_batch_sales (batch_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'hen_batch_sales_batch_id_fkey'
    ) THEN
        ALTER TABLE ONLY public.hen_batch_sales
            ADD CONSTRAINT hen_batch_sales_batch_id_fkey
            FOREIGN KEY (batch_id) REFERENCES public.hen_batches(id) ON DELETE CASCADE;
    END IF;
END$$;

DROP TRIGGER IF EXISTS trigger_update_batch_count_on_sale ON public.hen_batch_sales;
CREATE TRIGGER trigger_update_batch_count_on_sale
AFTER INSERT ON public.hen_batch_sales
FOR EACH ROW EXECUTE FUNCTION public.update_batch_count_on_sale();
